#!/usr/bin/env bash
# Pre-edit hook: block hand edits to generated files.
# Exit 2 blocks the edit; stderr is shown to the editor as the reason.
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "protect-files hook needs jq to read the edit target; install jq." >&2
  exit 2
fi

FILE="$(jq -r '.tool_input.file_path // empty')"

case "$FILE" in
  */evidence/*)
    echo "Generated by scripts. Change data/synthetic/ and run: make evidence" >&2
    exit 2
    ;;
  */report/REPORT.pdf)
    echo "Generated from report/REPORT.md. Run: make pdf" >&2
    exit 2
    ;;
  */.secrets.baseline)
    echo "Regenerate with: detect-secrets scan --baseline .secrets.baseline" >&2
    exit 2
    ;;
  */docs/diagrams/*.svg | */docs/diagrams/*.png | */docs/assets/cover.png)
    echo "Exported diagram or cover. Edit the source in docs/diagrams/ and re-export." >&2
    exit 2
    ;;
esac
exit 0
