"""Render evidence files and the generated blocks of report/REPORT.md.

Everything is deterministic: the same data always gives byte-identical output, which is what `make check`
compares against the committed files.
"""

from __future__ import annotations

import csv
import io
import json
import re
import textwrap
from pathlib import Path

from wa_assess import backlog as backlog_mod
from wa_assess import metrics, scoring
from wa_assess.model import Assessment

BLOCK = re.compile(
    r"(<!-- BEGIN GENERATED: (?P<name>[a-z0-9:-]+) -->\n)(?P<body>.*?)(<!-- END GENERATED: (?P=name) -->)",
    re.DOTALL,
)
# Any BEGIN or END comment, however its keyword is spelled, so a block whose markers were both mistyped still counts.
MARKER = re.compile(r"<!--\s*(?:BEGIN|END)\b", re.IGNORECASE)
RISK_LABEL = {"high": "High", "medium": "Medium", "low": "Low", "none": "None"}
STATUS_LABEL = {"met": "Met", "partial": "Partial", "not_met": "Not met", "not_applicable": "Not applicable"}
BACKLOG_COLUMNS = (
    "rank",
    "key",
    "best_practice",
    "pillar",
    "question",
    "title",
    "status",
    "risk",
    "effort",
    "owner",
    "roadmap_days",
    "depends_on",
    "evidence",
    "recommendation",
)


def _wrap(text: str, indent: str = "") -> str:
    """Wrap prose at 120 characters so generated Markdown passes the same line-length rule as hand-written text."""
    return textwrap.fill(text, width=120, subsequent_indent=indent, break_long_words=False, break_on_hyphens=False)


def _cell(text: object) -> str:
    return str(text).replace("|", "\\|")


def _table(header: list[str], rows: list[list[object]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    lines += ["| " + " | ".join(_cell(value) for value in row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def _csv_safe(value: object) -> object:
    """Stop spreadsheet apps from running a cell as a formula when the backlog is imported."""
    if isinstance(value, str) and value[:1] in ("=", "+", "-", "@", "\t", "\r"):
        return "'" + value
    return value


def _json(data: object) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


class Renderer:
    def __init__(self, assessment: Assessment, repo_root: Path) -> None:
        self.assessment = assessment
        self.repo_root = repo_root
        window = int(assessment.workload["scope"]["observation_window_days"])
        self.figures = metrics.compute(repo_root, window)
        self.scores = scoring.summarize(assessment)
        self.backlog = backlog_mod.build(assessment, self.figures)
        self.keys = {entry.item.id: entry.key for entry in self.backlog}

    # Evidence files -------------------------------------------------------------------------------------------

    def backlog_csv(self) -> str:
        buffer = io.StringIO()
        writer = csv.DictWriter(buffer, fieldnames=BACKLOG_COLUMNS, lineterminator="\n")
        writer.writeheader()
        for entry in self.backlog:
            writer.writerow({k: _csv_safe(v) for k, v in entry.as_row(self.assessment).items()})
        return buffer.getvalue()

    def backlog_md(self) -> str:
        return (
            "# Harbor Goods risk-rated backlog\n\n"
            "Generated by `make evidence` from `data/synthetic/`. Fictional sample; do not edit by hand.\n\n"
            + self.block_backlog(full=True)
        )

    def roadmap_md(self) -> str:
        return (
            "# Harbor Goods 30/60/90-day roadmap\n\n"
            "Generated by `make evidence` from `data/synthetic/`. Fictional sample; do not edit by hand.\n\n"
            + self.block_roadmap(level=2)
        )

    def files(self) -> dict[str, str]:
        return {
            "evidence/metrics.json": _json(self.figures),
            "evidence/scores.json": _json(self.scores),
            "evidence/backlog.csv": self.backlog_csv(),
            "evidence/backlog.md": self.backlog_md(),
            "evidence/roadmap.md": self.roadmap_md(),
        }

    # Report blocks --------------------------------------------------------------------------------------------

    def block_summary(self) -> str:
        fw, dv = self.scores["framework"], self.scores["devops"]
        d, inc = self.figures["delivery"], self.figures["incidents"]
        buckets = {days: sum(e.bucket == days for e in self.backlog) for days in backlog_mod.BUCKETS}
        by_risk = [str(sum(e.item.risk == risk for e in self.backlog)) for risk in ("high", "medium", "low")]
        rows = [
            ["Well-Architected score (six pillars)", f"{fw['score_pct']}%"],
            ["DevOps lens score", f"{dv['score_pct']}%"],
            ["High-risk issues (HRI), framework and DevOps lens", f"{fw['hri']} and {dv['hri']}"],
            ["Medium-risk issues (MRI), framework and DevOps lens", f"{fw['mri']} and {dv['mri']}"],
            ["Best practices reviewed", str(fw["best_practices"] + dv["best_practices"])],
            ["Backlog items (high, medium, low)", f"{len(self.backlog)} ({', '.join(by_risk)})"],
            ["Items planned for 30, 60 and 90 days", ", ".join(str(buckets[d_]) for d_ in backlog_mod.BUCKETS)],
            ["Deployments per week", str(d["deploys_per_week"])],
            ["Change failure rate", f"{d['change_failure_rate_pct']}%"],
            ["Median time to restore service", f"{inc['median_minutes_to_restore']} minutes"],
        ]
        return _table(["Measure", "Value"], rows)

    def block_headline(self) -> str:
        fw, dv = self.scores["framework"], self.scores["devops"]
        by_risk = [sum(e.item.risk == risk for e in self.backlog) for risk in ("high", "medium", "low")]
        high_questions = len({e.item.question for e in self.backlog if e.item.risk == "high"})
        return (
            _wrap(
                f"{fw['best_practices'] + dv['best_practices']} best practices reviewed, {len(self.backlog)} gaps: "
                f"{by_risk[0]} high, {by_risk[1]} medium and {by_risk[2]} low. Risk counts once per question, so the "
                f"{by_risk[0]} high-rated gaps across {high_questions} questions make {fw['hri'] + dv['hri']} "
                f"high-risk issues (HRI; {fw['hri']} in the framework, {dv['hri']} in the DevOps lens), plus "
                f"{fw['mri'] + dv['mri']} medium-risk issues (MRI). Well-Architected score {fw['score_pct']}%, "
                f"DevOps lens score {dv['score_pct']}%."
            )
            + "\n"
        )

    def block_pillar_scores(self, lens: str) -> str:
        rows = [
            [
                p["name"],
                f"{p['score_pct']}%",
                f"{p['maturity_level']} {p['maturity_name']}",
                p["met"],
                p["partial"],
                p["not_met"],
                p["hri"],
                p["mri"],
            ]
            for p in self.scores["pillars"]
            if p["lens"] == lens
        ]
        first = "Pillar" if lens == "wellarchitected" else "Lens"
        return _table([first, "Score", "Maturity", "Met", "Partial", "Not met", "HRI", "MRI"], rows)

    def block_top(self, count: int = 3) -> str:
        lines = [
            _wrap(
                f"{n}. **{e.item.title}** ({e.item.id}, {RISK_LABEL[e.item.risk]} risk, effort {e.item.effort}). "
                f"{e.recommendation}",
                indent="   ",
            )
            for n, e in enumerate(self.backlog[:count], start=1)
        ]
        return "\n".join(lines) + "\n"

    def block_findings(self, pillar_key: str) -> str:
        pillar = next(p for p in self.assessment.pillars if p.key == pillar_key)
        score = next(p for p in self.scores["pillars"] if p["key"] == pillar_key)
        risk_rows = [[q, pillar.questions[q], RISK_LABEL[risk]] for q, risk in score["question_risk"].items()]
        out = [_table(["Question", "Text", "Risk"], risk_rows)]
        for item in pillar.items:
            key = self.keys.get(item.id)
            heading = f"#### {item.id} {item.title}"
            meta = f"Status: {STATUS_LABEL[item.status]}"
            if item.is_gap:
                meta += f". Risk: {RISK_LABEL[item.risk]}. Effort: {item.effort}. Owner: {item.owner}. Backlog: {key}"
            meta += f". Evidence: {', '.join(item.evidence)}."
            body = [heading, "", _wrap(meta), "", _wrap(metrics.fill(item.observation, self.figures))]
            if item.is_gap:
                body += ["", _wrap("Recommendation: " + metrics.fill(item.recommendation or "", self.figures))]
            out.append("\n" + "\n".join(body) + "\n")
        return "".join(out)

    def block_backlog(self, full: bool = False) -> str:
        header = ["Rank", "Key", "Best practice", "Title", "Risk", "Effort", "Owner", "Days"]
        rows = []
        for e in self.backlog:
            row = [
                e.rank,
                e.key,
                e.item.id,
                e.item.title,
                RISK_LABEL[e.item.risk],
                e.item.effort,
                e.item.owner,
                e.bucket,
            ]
            if full:
                row += [" ".join(self.keys[d] for d in e.item.depends_on) or "-", e.recommendation]
            rows.append(row)
        if full:
            header += ["Depends on", "Recommendation"]
        return _table(header, rows)

    def block_roadmap(self, level: int = 3) -> str:
        titles = {30: "First 30 days", 60: "Days 31 to 60", 90: "Days 61 to 90"}
        out = []
        for days, entries in backlog_mod.roadmap(self.backlog).items():
            out.append(f"{'#' * level} {titles[days]} ({len(entries)} items)\n\n")
            for e in entries:
                moved = " Moved forward because later work depends on it." if e.bucket < e.base_bucket else ""
                deps = [self.keys[d] for d in e.item.depends_on]
                after = f" After {', '.join(deps)}." if deps else ""
                line = (
                    f"- {e.key} {e.item.title} ({e.item.id}, {RISK_LABEL[e.item.risk]}, {e.item.effort}), "
                    f"{e.item.owner}.{after}{moved}"
                )
                out.append(_wrap(line, indent="  ") + "\n")
            out.append("\n")
        return "".join(out).rstrip("\n") + "\n"

    def block_evidence(self) -> str:
        cited: dict[str, list[str]] = {}
        for item in self.assessment.items():
            for ev in item.evidence:
                cited.setdefault(ev, []).append(item.id)
        rows = [
            [ev_id, entry["kind"], entry["title"], entry.get("source", "-"), len(cited.get(ev_id, []))]
            for ev_id, entry in self.assessment.evidence.items()
        ]
        return _table(["ID", "Kind", "Description", "Source file", "Cited by"], rows)

    def block(self, name: str) -> str:
        if name.startswith("findings:"):
            return self.block_findings(name.split(":", 1)[1])
        blocks = {
            "summary": self.block_summary,
            "headline": self.block_headline,
            "top-recommendations": self.block_top,
            "pillar-scores": lambda: self.block_pillar_scores("wellarchitected"),
            "devops-scores": lambda: self.block_pillar_scores("devops"),
            "backlog": self.block_backlog,
            "roadmap": self.block_roadmap,
            "evidence-register": self.block_evidence,
        }
        if name not in blocks:
            raise KeyError(f"unknown generated block {name!r}")
        return blocks[name]()

    def report(self, text: str) -> str:
        """Return the report with every generated block re-rendered; prose outside the markers is kept."""
        markers = len(MARKER.findall(text))
        if markers != 2 * len(BLOCK.findall(text)):
            raise ValueError("a GENERATED marker is malformed or unpaired; fix it so the block is re-rendered")
        return BLOCK.sub(lambda m: m.group(1) + "\n" + self.block(m["name"]) + "\n" + m.group(4), text)
